export const ADVENTURE_TYPES = [
  {
    id: 'defis_fantastiques',
    name: 'Défis Fantastiques',
    description: 'La série classique (Le Sorcier de la Montagne de Feu, La Citadelle du Chaos, etc.)',
    statPreview: 'HABILETÉ (1D6+6) · ENDURANCE (2D6+12) · CHANCE (1D6+6)',
    stats: [
      { key: 'habilete', name: 'Habileté', dice: 1, bonus: 6 },
      { key: 'endurance', name: 'Endurance', dice: 2, bonus: 12 },
      { key: 'chance', name: 'Chance', dice: 1, bonus: 6 },
    ],
    combatSkill: 'habilete',
    combatStamina: 'endurance',
    hasProvisions: true,
    defaultProvisions: 10,
    potions: [
      { name: "Potion d'Adresse", effect: 'Restaure Habileté initiale', stat: 'habilete', doses: 2 },
      { name: 'Potion de Vigueur', effect: 'Restaure Endurance initiale', stat: 'endurance', doses: 2 },
      { name: 'Potion de Bonne Fortune', effect: 'Restaure Chance initiale + 1', stat: 'chance', doses: 2 },
    ],
    mealRestore: 4,
    special: null,
  },
  {
    id: 'sorcellerie',
    name: 'Sorcellerie!',
    description: 'La saga épique de Steve Jackson (Les Collines Maléfiques, La Cité des Pièges, etc.)',
    statPreview: 'HABILETÉ (1D6+6) · ENDURANCE (2D6+12) · CHANCE (1D6+6) · MAGIE',
    stats: [
      { key: 'habilete', name: 'Habileté', dice: 1, bonus: 6 },
      { key: 'endurance', name: 'Endurance', dice: 2, bonus: 12 },
      { key: 'chance', name: 'Chance', dice: 1, bonus: 6 },
    ],
    combatSkill: 'habilete',
    combatStamina: 'endurance',
    hasProvisions: true,
    defaultProvisions: 10,
    potions: [],
    mealRestore: 4,
    special: {
      title: 'Magie',
      type: 'spells',
      description: 'Notez vos sorts connus et leurs coûts en ENDURANCE',
    },
  },
  {
    id: 'loup_solitaire',
    name: 'Loup Solitaire',
    description: 'Les aventures du dernier des Seigneurs Kaï (Les Maîtres des Ténèbres, etc.)',
    statPreview: 'COMBAT (1D10+10) · ENDURANCE (20+1D10) · Disciplines Kaï',
    stats: [
      { key: 'combat', name: 'Habileté au Combat', dice: 1, bonus: 10, diceType: 10 },
      { key: 'endurance', name: 'Endurance', dice: 1, bonus: 20, diceType: 10 },
    ],
    combatSkill: 'combat',
    combatStamina: 'endurance',
    hasProvisions: true,
    defaultProvisions: 3,
    potions: [],
    mealRestore: 0,
    special: {
      title: 'Disciplines Kaï',
      type: 'checklist',
      items: [
        'Camouflage', 'Chasse', 'Sixième Sens', 'Orientation', 'Guérison',
        'Maîtrise des Armes', 'Bouclier Psychique', 'Puissance Psychique',
        'Communication Animale', 'Maîtrise du Corps',
      ],
      maxChoices: 5,
      description: 'Choisissez 5 Disciplines Kaï',
    },
  },
  {
    id: 'quete_graal',
    name: 'Quête du Graal',
    description: 'Aventures arthuriennes (Le Château des Ténèbres, etc.)',
    statPreview: 'HABILETÉ (1D6+6) · ENDURANCE (2D6+12) · CHANCE (1D6+6) · HONNEUR',
    stats: [
      { key: 'habilete', name: 'Habileté', dice: 1, bonus: 6 },
      { key: 'endurance', name: 'Endurance', dice: 2, bonus: 12 },
      { key: 'chance', name: 'Chance', dice: 1, bonus: 6 },
    ],
    combatSkill: 'habilete',
    combatStamina: 'endurance',
    hasProvisions: true,
    defaultProvisions: 10,
    potions: [],
    mealRestore: 4,
    special: {
      title: 'Honneur',
      type: 'counter',
      initial: 6,
      description: "Points d'Honneur du chevalier",
    },
  },
  {
    id: 'dragon_or',
    name: "Dragon d'Or",
    description: 'Série héroïque-fantasy avec métamorphoses (Le Fléau de la Plaine Ardente, etc.)',
    statPreview: 'VIGUEUR (2D6+12) · PSY (2D6+6) · AGILITÉ (1D6+6)',
    stats: [
      { key: 'vigueur', name: 'Vigueur', dice: 2, bonus: 12 },
      { key: 'psy', name: 'Psy', dice: 2, bonus: 6 },
      { key: 'agilite', name: 'Agilité', dice: 1, bonus: 6 },
    ],
    combatSkill: 'agilite',
    combatStamina: 'vigueur',
    hasProvisions: false,
    defaultProvisions: 0,
    potions: [],
    mealRestore: 0,
    special: {
      title: 'Métamorphose',
      type: 'transform',
      description: 'Formes alternatives et pouvoirs de transformation',
    },
  },
  {
    id: 'loup_ardent',
    name: 'Loup* Ardent / Chroniques Crétoises',
    description: 'Aventures mythologiques et autres séries',
    statPreview: 'HABILETÉ (1D6+6) · ENDURANCE (2D6+12) · CHANCE (1D6+6) · POUVOIR',
    stats: [
      { key: 'habilete', name: 'Habileté', dice: 1, bonus: 6 },
      { key: 'endurance', name: 'Endurance', dice: 2, bonus: 12 },
      { key: 'chance', name: 'Chance', dice: 1, bonus: 6 },
    ],
    combatSkill: 'habilete',
    combatStamina: 'endurance',
    hasProvisions: true,
    defaultProvisions: 10,
    potions: [],
    mealRestore: 4,
    special: {
      title: 'Pouvoir Spécial',
      type: 'power',
      description: 'Points de pouvoir magique ou divin',
    },
  },
  {
    id: 'custom',
    name: 'Personnalisé',
    description: "Configurez vos propres caractéristiques pour n'importe quel livre-jeu",
    statPreview: 'Caractéristiques libres',
    stats: [
      { key: 'stat1', name: 'Caractéristique 1', dice: 1, bonus: 6, editable: true },
      { key: 'stat2', name: 'Caractéristique 2', dice: 2, bonus: 12, editable: true },
      { key: 'stat3', name: 'Caractéristique 3', dice: 1, bonus: 6, editable: true },
    ],
    combatSkill: 'stat1',
    combatStamina: 'stat2',
    hasProvisions: true,
    defaultProvisions: 10,
    potions: [],
    mealRestore: 4,
    special: {
      title: 'Spécial',
      type: 'counter',
      initial: 0,
      description: 'Compteur spécial personnalisable',
    },
  },
];

export function getAdventureType(id) {
  return ADVENTURE_TYPES.find(a => a.id === id);
}
